version: '3.0'
services:
  runner-installer:
    image: buildbarn/bb-runner-installer:20200627T105551Z-fb9fa70
    volumes:
    - ./bb:/bb

  frontend:
    image: buildbarn/bb-storage:20200802T055539Z-f0281e2
    command:
    - /config/frontend.jsonnet
    ports:
    - "8980:8980"
    volumes:
    - ./config:/config

  storage-0:
    image: buildbarn/bb-storage:20200802T055539Z-f0281e2
    command:
    - /config/storage.jsonnet
    ports:
    - "8981:8981"
    volumes:
    - ./config:/config
    - ./storage-ac-0:/storage-ac
    - ./storage-cas-0:/storage-cas

  storage-1:
    image: buildbarn/bb-storage:20200802T055539Z-f0281e2
    command:
    - /config/storage-1.jsonnet
    ports:
    - "8982:8982"
    volumes:
    - ./config:/config
    - ./storage-ac-1:/storage-ac
    - ./storage-cas-1:/storage-cas

  scheduler:
    image: buildbarn/bb-scheduler:20200627T105551Z-fb9fa70
    command:
    - /config/scheduler.jsonnet
    ports:
    - "8983:8983"
    - "8984:8984"
    volumes:
    - ./config:/config

  runner-ubuntu16-04:
    image: l.gcr.io/google/rbe-ubuntu16-04@sha256:b516a2d69537cb40a7c6a7d92d0008abb29fba8725243772bdaf2c83f1be2272
    command:
    - sh
    - -c
    - while ! test -f /bb/installed; do sleep 1; done; exec /bb/tini -v -g -- /bb/bb_runner /config/runner-ubuntu16-04.jsonnet
    network_mode: none
    volumes:
    - ./worker-ubuntu16-04:/worker
    - ./config:/config
    - ./bb:/bb
    depends_on:
    - runner-installer

  browser:
    image: buildbarn/bb-browser:20200731T114407Z-e0d4436
    command:
    - /config/browser.jsonnet
    ports:
    - "6984:6984"
    volumes:
    - ./config:/config

  worker-ubuntu16-04:
    image: buildbarn/bb-worker:20200627T105551Z-fb9fa70
    command:
    - /config/worker-ubuntu16-04.jsonnet
    ports:
    - "7986:7986"
    volumes:
    - ./config:/config
    - ./worker-ubuntu16-04:/worker
    depends_on:
    - runner-ubuntu16-04

  bb-asset:
    image: bazel/cmd/bb_asset_hub:bb_asset_hub_container
    command: /config/asset.jsonnet
    ports:
    - "4401:4401"
    volumes:
    - "./storage-asset:/storage"
    - "./config:/config"

  buildstream:
    image: coldtom/buildstream:remote-asset
    privileged: true
    volumes:
    - "./bst-project:/bst-project"
    working_dir: /bst-project
    command:
    - ./test.sh
    depends_on:
    - runner-ubuntu16.04
    - frontend
    - storage-0
    - storage-1
    - scheduler
    - browser
    - worker-ubuntu16.04
    - bb-asset
